Hw9
AlexSpeal/tinkoff-java pull request #17
Opened 2023-12-10 20:21 UTC by AlexSpeal

2023-12-10 20:30 UTC, AlexSpeal commented
Не успел сделать 3е задание

2023-12-25 13:37 UTC, ZhekTheDark requested changes
привет! от тебя ждать 3е задание?

2023-12-25 13:37 UTC, ZhekTheDark commented on src/main/java/edu/hw3/Task1/Task1.java
> +public class Task1 {
старайся не комитить задания из других домашек

2023-12-25 13:37 UTC, ZhekTheDark commented on src/main/java/edu/hw9/Task1/Metric.java
> +    public double summ() {
sum

2023-12-28 11:33 UTC, merged